# @import ../global.http
# @ref host

###

POST {{host}}/users/signup
Content-Type: application/json

{
    "userName": "mhmdmsvi2",
    "email": "test2@gmail.com",
    "password": "pass3430",
    "confPassword": "pass3430"
}

{{
    $global.token=response.parsedBody.token
}}

POST {{host}}/users/login
Content-Type: application/json
Authorization: Bearer {{$global.token}}

{
    "email": "test2@gmail.com",
    "password": "pass3430"
}
