# @import ../global.http
# @ref host

###

POST {{host}}/user/signup
Content-Type: application/json

{
    "userName": "mhmdmsvi2",
    "email": "test2@gmail.com",
    "password": "pass3430",
    "confPassword": "pass3430"
}

{{
    $global.token=response.parsedBody.token
}}

POST {{host}}/user/login
Content-Type: application/json
Authorization: Bearer {{$global.token}}

{
    "email": "test2@gmail.com",
    "password": "pass3430"
}

POST {{host}}/user/forgotpass
Content-Type: application/json

{
    "email": "test2@gmail.com"
}

PATCH {{host}}/user/resetpass/
Content-Type: application/json

{
    "email": "test2@gmail.com"
}
